name: matrix_api_lite
description: Dead simple data model for the matrix.org client-server API.
version: 1.7.4
homepage: https://famedly.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  enhanced_enum: ^0.2.4
  http: ^1.2.1
  mime: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
